---
port: 8545
database: postgres://aurora:aurora@database/aurora
network: betanet
endpoint: https://rpc.betanet.near.org
engine: aurora
signer: relay.aurora
signerKey:
writable: true
natsUrl: "nats://europe.nats.backend.aurora.dev:4222"
natsChannel: "betanet.aurora.blocks"
natsCreds:
