---
port: 8545
database: postgres://aurora:aurora@database/aurora
network: mainnet
endpoint: https://archival-rpc.mainnet.near.org
engine: aurora
signer: relay.aurora
signerKey:
writable: true
natsUrl: "nats://europe.nats.backend.aurora.dev:4222"
natsChannel: "mainnet.aurora.blocks"
natsCreds:
