---
port: 8545
database: postgres://aurora:aurora@database/aurora
network: mainnet
endpoint: https://archival-rpc.mainnet.near.org
engine: aurora
signer: relay.aurora
signerKey:
writable: true
proxyMethods:
  url: "https://mainnet.aurora.dev"
  methods:
    - debug_traceTransaction
