---
port: 8545
database: postgres://aurora:aurora@database/aurora
network: testnet
endpoint: https://archival-rpc.testnet.near.org
engine: aurora
signer: relay.aurora
signerKey:
writable: true
natsUrl: "nats://europe.nats.backend.aurora.dev:4222"
natsChannel: "testnet.aurora.blocks"
natsCreds:
