FROM node:15-alpine
RUN mkdir -p /srv/aurora
RUN mkdir -p /srv/aurora/.near-credentials/mainnet
RUN mkdir -p /srv/aurora/.near-credentials/testnet
RUN mkdir -p /srv/aurora/.near-credentials/betanet
RUN ln -s testnet /srv/aurora/.near-credentials/default
RUN mkdir -p /srv/aurora/relayer
RUN chown -R node:node /srv/aurora
WORKDIR /srv/aurora/relayer
COPY --chown=node:node package*.json ./
USER node
RUN npm ci --only=production
COPY --chown=node:node . .
CMD ["node", "lib/index.js"]
EXPOSE 8545
